on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Publish Powershell Script
        uses: vertigo-one/publish-powershell-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
          path: src
